### ISSUE TITLE
Inp file upload problem.

### ISSUE THREAD

**Issue by Razaali100** [qgisred/QGISRed#120]
Hi dear,
I upload the inp file. See my snap. 
![Upload inp file](https://github.com/qgisred/QGISRed/assets/121994941/96bb63d9-af61-45d9-8c45-e9401986f0e8)
This is the error message.
![Error](https://github.com/qgisred/QGISRed/assets/121994941/e4040458-f2d6-4561-bf3a-2e32b3eaeb5a)
An error has occurred while executing Python code: 

TypeError: QgsLineSymbolLayer.setWidthUnit(): argument 1 has unexpected type 'int' 
Traceback (most recent call last):
  File "C:\Users/Raza Ali/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGISRed\ui\qgisred_import_dialog.py", line 215, in importInpProject
    self.parent.processCsharpResult(resMessage, "")
  File "C:\Users/Raza Ali/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGISRed\qgisred_plugins.py", line 2207, in processCsharpResult
    QGISRedUtils().runTask("update layers", self.removeLayers, self.runOpenTemporaryFiles)
  File "C:\Users/Raza Ali/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGISRed\tools\qgisred_utils.py", line 511, in runTask
    postprocess()
  File "C:\Users/Raza Ali/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGISRed\qgisred_plugins.py", line 2160, in runOpenTemporaryFiles
    QGISRedUtils().runTask("update layers", self.openElementLayers, self.setExtent)
  File "C:\Users/Raza Ali/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGISRed\tools\qgisred_utils.py", line 510, in runTask
    process(None)
  File "C:\Users/Raza Ali/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGISRed\qgisred_plugins.py", line 1764, in openElementLayers
    utils.openElementsLayers(inputGroup, self.ownMainLayers)
  File "C:\Users/Raza Ali/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGISRed\tools\qgisred_utils.py", line 74, in openElementsLayers
    self.openLayer(group, fileName)
  File "C:\Users/Raza Ali/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGISRed\tools\qgisred_utils.py", line 96, in openLayer
    self.setStyle(vlayer, name.lower())
  File "C:\Users/Raza Ali/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGISRed\tools\qgisred_utils.py", line 261, in setStyle
    lineSymbol.setWidthUnit(2)  # Pixels
TypeError: QgsLineSymbolLayer.setWidthUnit(): argument 1 has unexpected type 'int'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.34.0-Prizren Prizren, ffbdd67881 
Copy from error message window.
Python Path:
C:\Users/Raza Ali/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\wnt
C:/PROGRA~1/QGIS33~1.0/apps/qgis/./python
C:/Users/Raza Ali/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Raza Ali/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.0\apps\grass\grass83\etc\python
C:\Users\Raza Ali\Documents
C:\Program Files\QGIS 3.34.0\bin\python39.zip
C:\PROGRA~1\QGIS33~1.0\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib
C:\Program Files\QGIS 3.34.0\bin
C:\PROGRA~1\QGIS33~1.0\apps\Python39
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Raza Ali/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Raza Ali\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows
C:\Users\Raza Ali\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\giswater
C:\Users\Raza Ali\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\giswater\core\ui\..
C:\Users/Raza Ali/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ImportEpanetInpFiles/impcount.py
C:\Users\Raza Ali\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mapflow\dialogs\widgets
C:\Users\Raza Ali\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
My QGIS version is GIS version is 3.34.0-Prizren. My GISRED version is 0.16.
There is same issue with my another QGISRED version.
My QGIS version is GIS version is 3.26.2-Bunes Aires My GISRED version is 0.16.
The program hang after showing the issue.
Regards,

Raza Ali

**Comment by fmartine** [comment]
Dear Raza,

From the report it appears that you must be using version 3.34 of QGIS Prizren
"Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May 3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
QGIS version: 3.34.0-Prizren Prizren, ffbdd67881"

Probably you also have QGIS 3.26.2 version installed as you indicate at the end of the message, because both can coexist on the machine, but you have really logged in with 3.34

QGIS version 0.16 is incompatible with QGIS versions 3.3x onwards, and gives rise to the error you indicate.
We will soon release version 0.17 that solves this problem and provides many other improvements.
For now you will have to keep both versions of QGIS on your machine, and make sure that you start with QGIS 3.26 or 3.28 when you are going to use QGISRed

**Comment by balks** [comment]
See update in https://github.com/qgisred/QGISRed/issues/126
