### ISSUE TITLE
problem with QGISRED execution

### ISSUE THREAD

**Issue by apprenti1973** [qgisred/QGISRed#129]
hello 
I have this error when I apply de RUN EPANET under QGISRED . Please help me

2024-03-25T11:53:28     WARNING    Traceback (most recent call last):
              File "C:\Users/HP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGISRed\qgisred_plugins.py", line 2530, in runModel
              self.ResultDockwidget.simulate(self.ProjectDirectory, self.NetworkName)
              File "C:\Users/HP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGISRed\ui\qgisred_results_dock.py", line 800, in simulate
              self.saveCurrentRender()
              File "C:\Users/HP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGISRed\ui\qgisred_results_dock.py", line 272, in saveCurrentRender
              dictSce[openedLayerPath] = renderer.rootRule().clone()
             AttributeError: 'QgsSingleSymbolRenderer' object has no attribute 'rootRule'

**Comment by fmartine** [comment]
For those who want to use QGISRed with new QGIS versions after 3.28 and avoid the previous error you can download a new testing beta version 0.16.11 of QGISRed from the following link:
https://qgisred.upv.es/files/plugin/QGISRed_v0.16.11.zip

If you have a previous version (included 0.16.0):

Uninstall the QGISRed plugin from the QGis plugin manager.
Close QGis
Go to Windows Applications and Features and uninstall the application named QGISRed (I guess version 1.0.16.0)).
Follow the next steps.
If you have installed a version greater or equal than 0.16.1:

Download the zip from previous link
Open QGis and go to the Plugin Manager
Install the QGISRed plugin from ZIP (use the downloaded zip file)
When using it for first time, it will ask to install the new dependencies.
After installing them the webpage of QGISRed will be shown
Subscribe to the newsletter if desired and close de page.
If QGISRed icons are not shown in the toolbars, go again to the Plugin Manager, select the Installed tab and ensure that the checkbox of QGISRed is activated.
Good luck

**Comment by fmartine** [comment]
Indeed, the problem is due to the automatic creation of .qix files, a kind of spatial index designed to speed up the rendering of large-shape themes.  Although this is an option in the theme properties (Source, Geometry, Create Spatial Index), it seems the .qix files are created randomly because QGISRed does not create the themes with the QGIS tools, but directly from the shapelib library.  So far we have not been able to find out how to avoid the automatic creation of .qix files. Any suggestion is welcome.

**Comment by mcarvajalino** [comment]
Hi @fmartine,

Could you please update the link to v.0.16.11? The one you published here is not working any longer.

**Comment by MIJAIL18** [comment]
> En efecto, el problema se debe a la creación automática de archivos .qix, una especie de índice espacial diseñado para acelerar la representación de temas de formas grandes. Aunque se trata de una opción en las propiedades del tema (Fuente, Geometría, Crear índice espacial), parece que los archivos .qix se crean aleatoriamente porque QGISRed no crea los temas con las herramientas de QGIS, sino directamente desde la biblioteca shapelib. Hasta el momento no hemos podido averiguar cómo evitar la creación automática de archivos .qix. Cualquier sugerencia es bienvenida.

Professor Fernando, I solved the problem by updating the creation of spatial indexes every time I trace the pipes. I do it through the python console with the following code:
processing.run("native:createspatialindex", {'INPUT':'D:/11. MERISS/0.Data_Quehue/25.Qgisred/Red_Riego_Ccollana_Quehue_Pipes.shp'})
processing.run("native:createspatialindex", {'INPUT':'D:/11. MERISS/0.Data_Quehue/25.Qgisred/Red_Riego_Ccollana_Quehue_Junctions.shp'})

**Comment by MIJAIL18** [comment]
Professor Fernando, I solve the problem, updating the spatial indices every time a pipe or node is created through the python console in Qgis, with the following code, referenced to my work folder:

processing.run("native:createspatialindex", {'INPUT':'D:/11. MERISS/0.Data_Quehue/25.Qgisred/Red_Riego_Ccollana_Quehue_Pipes.shp'})
processing.run("native:createspatialindex", {'INPUT':'D:/11. MERISS/0.Data_Quehue/25.Qgisred/Red_Riego_Ccollana_Quehue_Junctions.shp'})

I think it is a problem of updating spatial indexes every time some network element is created. I didn't need to delete the qix file (just update it)
