### ISSUE TITLE
Uncaught TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'


### ISSUE THREAD

**Issue by koshtood** [qgisred/QGISRed#78]
Error while unloading plugin QGISRed
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS 3.16.16/apps/qgis-ltr/./python\qgis\utils.py", line 434, in unloadPlugin
    plugins[packageName].unload()
  File "C:\Users/Nubantood.Khalil/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGISRed\qgisred_plugins.py", line 596, in unload
    # Connecting QGis Events
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

```
QGISRed 0.14, QGIS 3.16.16-Hannover on Windows 10

**Comment by neslerel** [comment]
Hi @koshtood,

Thank for your message. However, I don't see the steps to reproduce the error. If you have tried to attach images, they don't appear in your message... Please, try again or try to write the steps with words...
