### ISSUE TITLE
Error when open an inp file

### ISSUE THREAD

**Issue by agua1990** [qgisred/QGISRed#89]
hello 

When i try to open an inp file i have an error for some files

Error: Object reference not set to an instance of an object. at GISRed.Model.Readers.FromInp.?????????????????????????????????????????() at GISRed.Model.Readers.FromInp.?????????????????????????????????????????() at GISRed.Model.Readers.FromInp.ReadInp(String inpFile, Boolean allInp) at GISRed.ExtendedModel.ExtendedScenario.ReadExtendedInp(Logger logger, String inpFile) at GISRed.QGisPlugins.QGisPlugins.ImportFromInp(String dirPath, String networkName, String tempPath, String inpFile, String epsg)

do you have any idea why there is this error for certain  inp files ?

this error with (1.0.16/1.0.16.2)

**Comment by neslerel** [comment]
To debug the error we will need the inp file. Could you send one of them to qgisred@upv.es?

**Comment by agua1990** [comment]
I just found the solution to the problem, in the .inp there is the source quality  without a time model and this is the cause of the problem. by adding it it works
(you can close the issue)

**Comment by wciezak** [comment]
Hello, missing source pattern still causes error (version 1.0.16.7):

CRITICAL    Error : Object reference not set to an instance of an object. at GISRed.Model.Readers.FromInp.?????????????????????????????????????????() 
              at GISRed.Model.Readers.FromInp.?????????????????????????????????????????() 
              at GISRed.Model.Readers.FromInp.ReadInp(String inpFile, Boolean allInp) 
              at GISRed.ExtendedModel.ExtendedScenario.ReadExtendedInp(Logger logger, String inpFile) 
              at GISRed.QGisPlugins.QGisPlugins.ImportFromInp(String dirPath, String networkName, String tempPath, String inpFile, String epsg)

-->
[SOURCES]
;Node            	Type        	Quality     	**_Pattern_**
 ZBD-1           	CONCEN      	0.3     
-->

INP file to download at the link: [https://www.wciezak.eu/!download/net-01.inp](INP-test)

**Comment by wciezak** [comment]
Hello again. Reinstalling the plugin along with the dll files solved the problem. Now the file imports correctly without error. Sorry for the confusion.

**Comment by Neibafh** [comment]
Hello

When i try to open an inp file i have an error for some files

Error: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource) at GISRed.Model.Misc.Rule.CombineConditionsFromInp(List`1 operators) at GISRed.Model.Readers.FromInp.?????????????????????????????????????????() at GISRed.Model.Readers.FromInp.ReadInp(String inpFile, Boolean allInp) at GISRed.ExtendedModel.ExtendedScenario.ReadExtendedInp(Logger logger, String inpFile) at GISRed.QGisPlugins.QGisPlugins.ImportFromInp(String dirPath, String networkName, String tempPath, String inpFile, String epsg)

do you have any idea why there is this error for certain inp files ?
I've send my INP to you at qgisred@upv.es.
